export const SES_REGIONS = [
    {value: "us-east-1", label: "US East (N. Virginia)"},
    {value: "us-east-2", label: "US East (Ohio)"},
    {value: "us-west-1", label: "US West (N. California)"},
    {value: "us-west-2", label: "US West (Oregon)"},
    {value: "ap-south-1", label: "Asia Pacific (Mumbai)"},
    {value: "ap-southeast-1", label: "Asia Pacific (Singapore)"},
    {value: "ap-southeast-2", label: "Asia Pacific (Sydney)"},
    {value: "ap-northeast-1", label: "Asia Pacific (Tokyo)"},
    {value: "ap-northeast-2", label: "Asia Pacific (Seoul)"},
    {value: "ca-central-1", label: "Canada (Central)"},
    {value: "eu-central-1", label: "Europe (Frankfurt)"},
    {value: "eu-west-1", label: "Europe (Ireland)"},
    {value: "eu-west-2", label: "Europe (London)"},
    {value: "sa-east-1", label: "South America (São Paulo)"},
];